# Generated by Django 4.0.4 on 2022-04-23 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0003_remove_customer_customer_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('picture', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_list', models.CharField(blank=True, max_length=10000)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('payment_mode', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('oder_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jutshirt_app.customer')),
            ],
        ),
    ]
