# Generated by Django 4.0.4 on 2022-04-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0004_products_oder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
