# Generated by Django 4.0.4 on 2022-04-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0006_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
