# Generated by Django 4.0.4 on 2022-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0007_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='quantity_list',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='oder',
            name='size_list',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
