# Generated by Django 4.0.4 on 2022-04-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0008_oder_quantity_list_oder_size_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
