# Generated by Django 4.0.4 on 2022-04-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jutshirt_app', '0009_remove_products_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
    ]
